### ISSUE TITLE
How to use qemu running minos?

### ISSUE THREAD

**Issue by wuxiaoqiang12** [minosproject/minos#1]
I want to use qemu to run the minos for gdb-debug.

**Comment by lemin9538** [comment]
I am not run minos on qemu currently,  if you want do gdb debug,  you can use arm fvp or DS5, or you can help enable on minos. Thanks

**Comment by wuxiaoqiang12** [comment]
I'm happy to help you to enhance the minos.
I'm trying to using qemu run your minos. It's almost done. But I face a problem:
I don't know the load address and entry address of minos. Such that the u-boot cannot boot the minos.

**Comment by lemin9538** [comment]
Good, The load address is simple to caculate.  For example: 

If the memory space for Minos is: 0x10000000 - 0x20000000

Then the entry and load address should be  0x10000000 + NR_CPUs * 0x2000. 

Each idle task will have 8k stack now.  You can refers to platform/fvp/Kconfig. Thanks

**Comment by wuxiaoqiang12** [comment]
Yes, that is right. Thank you. Now I face another problem with dtb. I set the boot.scr of u-boot with dtb_load_address is 0x03e000000 from your old-version of Readme. But it seems not right. I loaded the minos at 0x20008000. I use gdb to see why it stuck at u-boot transfer the control of system to the minos. It seems like the dtb is not properly loaded.

**Comment by lemin9538** [comment]
can you use fatload or ext4load directly  in your u-boot to check wheter it has been load correctly?

for example:
fatload 0x28008000 minos.bin
fatload 0x2BE00000 minos.dtb
booti 0x28008000 - 0x2BE00000

I just test booti command in u-boot, so I am not sure if use boot.src will have some issue, since i did not test .src file in u-boot. thanks.

**Comment by wuxiaoqiang12** [comment]
Does it must have a linux Image? I just provide the minos.bin and bcm2837-rpi-3-b-plus.dtb to u-boot. It will stuck at pr_notice function. Thanks a lot.

**Comment by lemin9538** [comment]
可以不需要，你把CONFIG_SHELL打开，会进一个简单的SHELL. 

因为rpi3很久没维护了，可能VM启动会有点问题，正好你也可以帮忙验证下:)

**Comment by lemin9538** [comment]
rpi3 has tested on latest code, you can refers to https://github.com/minosproject/minos/blob/master/Documents/009-Test_Minos_on_Raspberry_3B.md
