### ISSUE TITLE
host vm / guest vm 网络不通

### ISSUE THREAD

**Issue by liuzuanmin** [minosproject/minos#11]
1. 创建guest的命令:
mvm vcpus=1 memory=96 bootimage=aarch64-boot.img vm_name=guest1 vm_os=linux os-64bit  gic=gicv2 device@virtio_console,backend=@pty device@virtio_net,tap0 cmdline="console=hvc0 loglevel=8 consolelog=9 root=/dev/vda2 rw"
2. 在host vm可以看到tap0设备，而且也可以配置ip
ifconfig tap0 192.168.1.10 up

3. guest里也可以看到 eth0
ifconfig eth0 192.168.1.11 up

两个网卡ping不通。

请教一下：
1. virtio_net在最新的代码上能ping通吗？
2. host vm /dev/net/tun跟guest vm eth0感觉不是同一层的设备，tap0感觉是层三的模拟设备，eth0感觉是层二的模拟设备，我的理解对吗？

还望多多指导。

**Comment by lemin9538** [comment]
- virtio_net在最新的代码上能ping通吗？
  virtio-net这块当前没有调通过。当前还没法ping通

- host vm /dev/net/tun跟guest vm eth0感觉不是同一层的设备，tap0感觉是层三的模拟设备，eth0感觉是层二的模拟设备，我的理解对吗？
网络这块我没有深入研究过。当前minos采用的网络方案理论上是可以工作的，在host需要设置把桥接配置起来。

如果有兴趣的话，欢迎帮忙调试下，也非常期待能加入这个项目:)，现在这个项目正需要像你这样的人才。

**Comment by liuzuanmin** [comment]
> 如果有兴趣的话，欢迎帮忙调试下，也非常期待能加入这个项目:)，现在这个项目正需要像你这样的人才。
谢谢快速回复。
我先调研下，看问题出在哪儿，有结果了就在这儿update。
![image](https://user-images.githubusercontent.com/6505472/82904799-8d6e9700-9f95-11ea-9300-0e1a12a73312.png)

**Comment by lemin9538** [comment]
- 在host vm可以看到tap0设备，而且也可以配置ip
ifconfig tap0 192.168.1.10 up

不应该直接给tap0配ip的，需要建立一个桥接， 然后把tap0加入到桥接。配置成类似以下

minos-br0 Link encap:Ethernet HWaddr B2:50:41:FE:F7:A3
   inet addr:10.239.154.43 Bcast:10.239.154.255 Mask:255.255.255.0
   inet6 addr: fe80::b050:41ff:fefe:f7a3/64 Scope:Link
   UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
   RX packets:226932 errors:0 dropped:21383 overruns:0 frame:0
   TX packets:14816 errors:0 dropped:0 overruns:0 carrier:0
   collisions:0 txqueuelen:1000
   RX bytes:100457754 (95.8 Mb) TX bytes:83481244 (79.6 Mb)

tap0 Link encap:Ethernet HWaddr F6:A7:7E:52:50:C6
   UP BROADCAST MULTICAST MTU:1500 Metric:1
   RX packets:0 errors:0 dropped:0 overruns:0 frame:0
   TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
   collisions:0 txqueuelen:1000
   RX bytes:0 (0.0 b) TX bytes:0 (0.0 b)

enp3s0 Link encap:Ethernet HWaddr 98:4F:EE:14:5B:74
   inet6 addr: fe80::9a4f:eeff:fe14:5b74/64 Scope:Link
   UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
   RX packets:279174 errors:0 dropped:0 overruns:0 frame:0
   TX packets:69923 errors:0 dropped:0 overruns:0 carrier:0
   collisions:0 txqueuelen:1000
   RX bytes:107312294 (102.3 Mb) TX bytes:87117507 (83.0 Mb)
   Memory:82200000-8227ffff

lo Link encap:Local Loopback
   inet addr:127.0.0.1 Mask:255.0.0.0
   inet6 addr: ::1/128 Scope:Host
   UP LOOPBACK RUNNING MTU:65536 Metric:1
   RX packets:16 errors:0 dropped:0 overruns:0 frame:0
   TX packets:16 errors:0 dropped:0 overruns:0 carrier:0
   collisions:0 txqueuelen:1000
   RX bytes:1216 (1.1 Kb) TX bytes:1216 (1.1 Kb)

**Comment by liuzuanmin** [comment]
如下是guest进行ping的日志输出，在mvm里拿到了数据，但是被如下代码逻辑扔掉了。
帮忙看下是否应该从iovec[1]还是iovec[0]开始，另外iovec[0]里的前12bytes也感觉是多余的。
[NIC  ] virtio: packet send, 54 0 bytes, 1 segs

﻿pr_notice("virtio: packet send, %d %d bytes, %d segs\n\r", tlen, plen, out);
net->virtio_net_tx(net, &vq->iovec[1], out - 1, plen);

APR协议
这些数据貌似多余，请check-----------
[NIC  ] virtio: iovec[0][0]:  0
[NIC  ] virtio: iovec[0][1]:  0
[NIC  ] virtio: iovec[0][2]:  0
[NIC  ] virtio: iovec[0][3]:  0
[NIC  ] virtio: iovec[0][4]:  0
[NIC  ] virtio: iovec[0][5]:  0
[NIC  ] virtio: iovec[0][6]:  0
[NIC  ] virtio: iovec[0][7]:  0
[NIC  ] virtio: iovec[0][8]:  0
[NIC  ] virtio: iovec[0][9]:  0
[NIC  ] virtio: iovec[0][10]:  0
[NIC  ] virtio: iovec[0][11]:  0
destionation mac-------------------
[NIC  ] virtio: iovec[0][12]: FF
[NIC  ] virtio: iovec[0][13]: FF
[NIC  ] virtio: iovec[0][14]: FF
[NIC  ] virtio: iovec[0][15]: FF
[NIC  ] virtio: iovec[0][16]: FF
[NIC  ] virtio: iovec[0][17]: FF
source mac------------------------
[NIC  ] virtio: iovec[0][18]:  0
[NIC  ] virtio: iovec[0][19]: 11
[NIC  ] virtio: iovec[0][20]: 22
[NIC  ] virtio: iovec[0][21]: 33
[NIC  ] virtio: iovec[0][22]: 44
[NIC  ] virtio: iovec[0][23]: 56
ARP--------------------------------
[NIC  ] virtio: iovec[0][24]:  8
[NIC  ] virtio: iovec[0][25]:  6
hardwar type: ethernet------------
[NIC  ] virtio: iovec[0][26]:  0
[NIC  ] virtio: iovec[0][27]:  1
protocol type:IPv4----------------
[NIC  ] virtio: iovec[0][28]:  8
[NIC  ] virtio: iovec[0][29]:  0
hardware size-----
[NIC  ] virtio: iovec[0][30]:  6
protocol size-------
[NIC  ] virtio: iovec[0][31]:  4
opcode---------------------------
[NIC  ] virtio: iovec[0][32]:  0
[NIC  ] virtio: iovec[0][33]:  1
sender mac------------------------
[NIC  ] virtio: iovec[0][34]:  0
[NIC  ] virtio: iovec[0][35]: 11
[NIC  ] virtio: iovec[0][36]: 22
[NIC  ] virtio: iovec[0][37]: 33
[NIC  ] virtio: iovec[0][38]: 44
[NIC  ] virtio: iovec[0][39]: 56
sender ip-------------------------
[NIC  ] virtio: iovec[0][40]: C0
[NIC  ] virtio: iovec[0][41]: A8
[NIC  ] virtio: iovec[0][42]:  1
[NIC  ] virtio: iovec[0][43]: 65
target mac------------------------
[NIC  ] virtio: iovec[0][44]:  0
[NIC  ] virtio: iovec[0][45]:  0
[NIC  ] virtio: iovec[0][46]:  0
[NIC  ] virtio: iovec[0][47]:  0
[NIC  ] virtio: iovec[0][48]:  0
[NIC  ] virtio: iovec[0][49]:  0
target ip-------------------------
[NIC  ] virtio: iovec[0][50]: C0
[NIC  ] virtio: iovec[0][51]: A8
[NIC  ] virtio: iovec[0][52]:  1
[NIC  ] virtio: iovec[0][53]: 64
[NIC  ] virtio: packet send, 54 0 bytes, 1 segs

**Comment by lemin9538** [comment]
应该是要从iovec[1] 开始的,iovec[0]要舍弃掉。可以对比下正常ping收到的数据。

**Comment by liuzuanmin** [comment]
> 应该是要从iovec[1] 开始的,iovec[0]要舍弃掉。可以对比下正常ping收到的数据。

可是 APR的协议数据在 iovec[0]里，就被丢掉啦

**Comment by lemin9538** [comment]
👍🏻 不错，你看的还是挺仔细的。这块你可以深入研究下，看看能不能找到原因。当前virtio-console和virtio-blk都能工作，就差virtio-net。

**Comment by lemin9538** [comment]
兄弟 你微信号多少 我们加个微信？

**Comment by liuzuanmin** [comment]
> 兄弟 你微信号多少 我们加个微信？

可以尝试跳过hdr（12bytes），效果好很多。
