### ISSUE TITLE
Raspberry pi 3 Model B+

### ISSUE THREAD

**Issue by tanerfejzulovskii** [minosproject/minos#2]
Hello,
I was searching for the documentation for raspberry pi 3 model b+, but I couldn't find it in the Documents folder.
There was an installation guide in the previous repository, but once you move the code and readme here, I can't find anything about raspberry pi 3B+.
Can you please help?
Thanks in advance.

**Comment by lemin9538** [comment]
Hi,  There are some code rebase work for RPI3b+ in kernel,  The code and documents will updated soon.

**Comment by tanerfejzulovskii** [comment]
Thanks for your answer.

**Comment by lemin9538** [comment]
please follow https://github.com/minosproject/minos/blob/master/Documents/009-Test_Minos_on_Raspberry_3B.md

**Comment by tanerfejzulovskii** [comment]
It was faster than expected. I will try it.
Thanks a lot and keep up the great work!
