### ISSUE TITLE
 If I want to run on Raspberry Pi 4/2G, what configuration needs to be modified?

### ISSUE THREAD

**Issue by jason--liu** [minosproject/minos#24]
Hi, 
I want to run minos on Raspberry Pi 4 with 2G memory, and I have checked the relevant documents, but did not find the relevant instructions. So,  what configuration needs to be modified?
Thanks.

**Comment by lemin9538** [comment]
you need know the memory information of the board, and the memory usage for the linux. then modify below area to the correct value (dtbs/bcm2838-rpi-4-b-32bit.dts):
1 - the /memory node 
2 - the memory information of each vm in /vms

currently, you can try below patch, with this patch maybe the 2G version can work well directly without any other modification

diff --git a/dtbs/bcm2838-rpi-4-b-32bit.dts b/dtbs/bcm2838-rpi-4-b-32bit.dts
index b77a33a..d5bb56c 100644
--- a/dtbs/bcm2838-rpi-4-b-32bit.dts
+++ b/dtbs/bcm2838-rpi-4-b-32bit.dts
@@ -14,7 +14,6 @@
 
        chosen {
                minos,stdout = "bcm283x_mu";
-               extra-memory = <0x40000000 0xbc000000>;
                bootargs = "bootwait=3 tty=vm0";
        };
