### ISSUE TITLE
How to Run windows 10 (generic ARM64 image) on Khadas VIM3 on top of Minos

### ISSUE THREAD

**Issue by ZephyrLabs** [minosproject/minos#28]
Hi, 
I have just come to know about the Minos project and how it can virtualise many OS images and things like ZephyrRTOS

I'd also like to know if you can try to run the generic ARM64 windows 10 image using Minos on the Khadas VIM3 pro

any help to my question is grateful, 
Thank you

**Comment by lemin9538** [comment]
Hi

In theory, it is possible, but the workload will be huge.
