### ISSUE TITLE
编译mvm错误

### ISSUE THREAD

**Issue by zt449569708** [minosproject/minos#3]
错误提示：
Build Minos userspace tools for Virtual Machine
Compiling main/mvm.o ...
make[1]: aarch64-linux-gnu-gcc: Command not found
Makefile:67: recipe for target 'main/mvm.o' failed

因此minos/tools/mvm/Makefile 中的CROSS_COMPILE   := aarch64-linux-gnu- 的 := 应该改成 ?= ，因为在编译的时候可能已经指定了CROSS_COMPILE，名字不一定就是aarch64-linux-gnu-

**Comment by lemin9538** [comment]
请问 你这边是编译非arm64平台嘛？当前代码只支持arm64

make[1]: aarch64-linux-gnu-gcc: Command not found
你这个错误是aarch64-linux-gnu-gcc没有找到，你是否有安装交叉编译工具？你可以 which aarch64-linux-gnu-gcc查看下。

你指出的建议也非常好，后面会修改位 ?= 谢谢

**Comment by zt449569708** [comment]
我的是树莓派4，但我的交叉编译链名字前缀是aarch64-none-linux-gnu-，所以就出现了这个问题make[1]: aarch64-linux-gnu-gcc: Command not found

**Comment by lemin9538** [comment]
Ok. 了解

如果是用树莓派32位系统的话，注意mvm要编译成32位
