### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by fxsheep** [minosproject/minos#37]
commit https://github.com/minosproject/minos/commit/a001ec70852d34a46e8cd1623ee16c047c0e8a90 is causing following compilation errors:
> make[1]：Wall：命令未找到
> make[1]: [scripts/Minos.build.mk:88：core/bitmap.o] 错误 127 (已忽略）

**Comment by fxsheep** [comment]
should be ?= $(CROSS_COMPILE)

**Comment by lemin9538** [comment]
@wangqiang624731186 could you please have a check.

**Comment by lemin9538** [comment]
a001ec7 is revered.

**Comment by wangqiang624731186** [comment]
> @wangqiang624731186 could you please have a check.
不好意思，我使用自己的SDK的编译器没有报错，忘了使用你这边的编译器测试了，确实有问题
