### ISSUE TITLE
Compile minos for arm fvp

### ISSUE THREAD

**Issue by wuxiaoqiang12** [minosproject/minos#4]
I can run minos on RPI3 real machine. I following the instruction at [run-minos-on-arm-fvp](https://github.com/minos-project/minos-hypervisor/tree/9429eb1b3c719550ef5af27d27ebe5d1982bbd9b#run-minos-on-arm-fvp) to run the minos on arm fvp. But the `bl31.bin` will not be generated. I delete the `ENABLE_PIE=0` when building the arm-trusted-firmware. It will be generated. But ssh cannot be connect to arm-fvp. Could you write the Test_Minos_on_ARM_FVP.md when you avaliable? Thank you very much.

**Comment by lemin9538** [comment]
arm fvp上的ssh视乎是有点问题，我这边在ubuntu 14.04上和ubuntu18.04上是可以用的，但是在ubuntu 16.04上没法用、

你可以看看换个端口，看看端口有没有被防火墙限制。
另外，arm-fvp的virtio image是否有加载?

**Comment by wuxiaoqiang12** [comment]
感谢回复。 我使用的是Ubuntu19.10, 我更换了确定可以使用的端口也不行，使用ssh -p [port] root@127.0.0.1 后没有任何反应. 应该不是端口被限制的问题。是否时因为我在构建arm-trusted-firmware的时候去掉了参数ENABLE_PIE=0的原因。virtio block image(sd.img)我给arm-fvp传了参数-C bp.virtioblockdevice.image_path=sd.img。应该是加载了。

**Comment by lemin9538** [comment]
这个跟atf没有关系。uart log是否有？能否截个图看看 我之前连不上是会报错的。会报 connection reset by peers 什么的。

下面是我当前使用的配置 在18.04上是可以连接上的.

-C pctl.startup=0.0.0.0 -C bp.secure_memory=0 -C cluster0.NUM_CORES=4 -C cache_state_modelled=0 -C cluster0.cpu0.RVBAR=0x04020000 -C cluster0.cpu1.RVBAR=0x04020000 -C cluster0.cpu2.RVBAR=0x04020000 -C cluster0.cpu3.RVBAR=0x04020000 -C bp.hostbridge.userNetPorts="8023=22" -C bp.hostbridge.userNetworking=true -C bp.dram_size=8 -C bp.smsc_91c111.enabled=true -C bp.virtioblockdevice.image_path=/home/minle/work/arm-fvp/sd.img --data cluster0.cpu0=/home/minle/work/arm-fvp/bl31.bin@0x04020000 --data cluster0.cpu0=/home/minle/work/arm-fvp/Image@0x80080000 --data cluster0.cpu0=/home/minle/work/arm-fvp/minos.bin@0xc0008000 --data cluster0.cpu0=/home/minle/work/arm-fvp/fdt.dtb@0xc3e00000 --data cluster0.cpu0=/home/minle/work/arm-fvp/fvp_linux.dtb@0x83e00000

**Comment by lemin9538** [comment]
我刚看了下代码， 当前配置使用的是debug console, debug console的代码没有完全upload, 还有些功能在开发中。你把vm0的cmdline改下，使用uart console:

		vm0 {

			cmdline = "console=hvc0 earlycon=dbcon,io,0x0 loglevel=8 consolelog=9 root=/dev/vda2 rw";

		};

改成
		vm0 {

			cmdline = "console=ttyAMA0 earlycon=pl011,0x1c090000 loglevel=8 consolelog=9 root=/dev/vda2 rw";

		};

这样你可以使用uart console.

**Comment by wuxiaoqiang12** [comment]
我改了uart console之后也是一样。我第一次使用arm-fvp不知道是不是哪里设置的不对。
![image](https://user-images.githubusercontent.com/39110174/76705821-458be380-66b9-11ea-9405-957a83dc16a5.png)
如上图所示，输入FVP_Base_AEMv8A代码之后会出现左侧的两个FVP terminal和一个Fast Models的窗口。在另一个terminal中我输入sudo ssh -p 8832 root@127.0.0.1不会有任何反应：
![image](https://user-images.githubusercontent.com/39110174/76705860-a9161100-66b9-11ea-929e-0f3b662e3e96.png)
有没有sudo都一样。还有一点是您的配置最后一个`fvp_linux.dtb`我不知道是那个dtb就没有加。

**Comment by wuxiaoqiang12** [comment]
还是说这就算连上了？因为我用Ctrl-c退出arm_fvp后ssh那边会如下提示：
![image](https://user-images.githubusercontent.com/39110174/76705915-1de94b00-66ba-11ea-9224-94507b889e60.png)
kex_exchange_identification: read: Connection reset by peer？

**Comment by wuxiaoqiang12** [comment]
我用DS-5调试好像是能连接上，但是可能是因为我不知道怎么在DS-5里面调试，step in源码窗口不会有运行到哪一步的指示。
![image](https://user-images.githubusercontent.com/39110174/76706988-0a41e280-66c2-11ea-9f89-fd231a81c17d.png)
像这样， 我也不知道对不对？我原本以为和其他IDE或者gdb一样

**Comment by wuxiaoqiang12** [comment]
刚进入DS-5的调试的时候，执行step in会报
ERROR(CMD440-TAD10-NAL23): 
! Stepping failed
! Failed to read 4 bytes from address EL3:0x0000000028008000
! Memory read from model failed.
的错误。

**Comment by lemin9538** [comment]
你这个快要成功了。
0x0000000028008000 读写错误是因为你在arm-fvp上使用了raspberry-pi3的镜像，你需要编译一个arm-fvp的minos.bin

# make distclean
# make fvp_defconfig
# make && make dtb
我脚本里面的fdt.dtb对应源码里面的dtbs/dtbs/foundation-v8-gicv3.dtb
fvp_linux.dtb 是linux(VM0)的device tree. 可以在https://github.com/minosproject/minos-misc/tree/master/arm-fvp里面找到。

linux的Image你下载linux-marvell这个仓库进行编译。

另外如果你要单步的话，可以用 make O=0 编译minos, 默认会进行O2优化。

由于这几天项目忙，后面有空会更新arm-fvp和ds5的指南，你先照我上面说的步骤试试看。

**Comment by wuxiaoqiang12** [comment]
非常感谢您的回复。我试了一下确实可以了。step in 也能正常工作。Thank you very much！

**Comment by lemin9538** [comment]
Ok I will close this issue. Thanks
