### ISSUE TITLE
When DS-5 encount tlbi instruction or pr_notice the debug tracker failed.

### ISSUE THREAD

**Issue by wuxiaoqiang12** [minosproject/minos#5]
As the title mentioned, for the tlbi instruction fail(DS-5 will running forever) I comment in the tlbi instruct. But the another one, I cannot do comment in, there are lots of pr_notice. Did you face this issue? 

When I interrupt the running the infomation as following：
Execution stopped in EL3h mode at EL3:0x0000000000000200
On core ARMAEMv8-A_MP_0 (ID 0)
EL3:0x0000000000000200   DCI      0xe7ff0010 ; ? Undefined

**Comment by lemin9538** [comment]
这个应该是你的DS5配置问题导致的，代码在minos上是没有问题的，请确保以下地方配置正确:
![Screenshot from 2020-03-16 23-12-05](https://user-images.githubusercontent.com/1614365/76772535-030ef780-67dc-11ea-90f4-17f7d39fa71c.png)
![Screenshot from 2020-03-16 23-12-53](https://user-images.githubusercontent.com/1614365/76772547-0904d880-67dc-11ea-8245-3e52665bb3d3.png)

Model parameters里面的参数为上个issue里面我发的那个

**Comment by wuxiaoqiang12** [comment]
我这里的设置应该是对的，我估计是我DS-5的版本的问题。请问你的DS5是什么版本

**Comment by lemin9538** [comment]
make PLAT=fvp RESET_TO_BL31=1 ARM_LINUX_KERNEL_AS_BL33=1 PRELOADED_BL33_BASE=**0xc0000000** ARM_PRELOADED_DTB_BASE=**0x83e00000**

上面两个地址改了吗？要改成0xc0008000 和0xc3e00000

**Comment by wuxiaoqiang12** [comment]
![image](https://user-images.githubusercontent.com/39110174/76779863-6bc98600-6782-11ea-9b6e-6435eb053008.png)
这里我使用的参数是改了地址的:
-C pctl.startup=0.0.0.0 -C bp.secure_memory=0 -C cluster0.NUM_CORES=4 -C cache_state_modelled=0 -C cluster0.cpu0.RVBAR=0x04020000 -C cluster0.cpu1.RVBAR=0x04020000 -C cluster0.cpu2.RVBAR=0x04020000 -C cluster0.cpu3.RVBAR=0x04020000 -C bp.hostbridge.userNetPorts="8023=22" -C bp.hostbridge.userNetworking=true -C bp.dram_size=8 -C bp.smsc_91c111.enabled=true -C bp.virtioblockdevice.image_path=/home/jon/minos-workspace/arm-fvp/sd.img --data cluster0.cpu0=/home/jon/minos-workspace/arm-fvp/bl31.bin@0x04020000 --data cluster0.cpu0=/home/jon/minos-workspace/arm-fvp/Image@0x80080000 --data cluster0.cpu0=/home/jon/minos-workspace/arm-fvp/minos.bin@0xc0008000 --data cluster0.cpu0=/home/jon/minos-workspace/arm-fvp/fdt.dtb@0xc3e00000

![image](https://user-images.githubusercontent.com/39110174/76779893-7e43bf80-6782-11ea-858c-22a6c3ee9145.png)
这里我这个版本的DS-5好像symbol file必须在这里添加才能debug。在下面的debugger里面添加不行。
![image](https://user-images.githubusercontent.com/39110174/76779980-a3d0c900-6782-11ea-91e6-525c3cebf15e.png)
这里我设置connect only开始调试之后我在_start打断点，然后continue，DS-5不会停止，会一直running。

**Comment by wuxiaoqiang12** [comment]
我刚才看错了， 你说的地址是构建arm-trust-firmware里面用的地址。这个地址我刚才改了下，但我现在生成不了bl31.bin。我再看看咋回事

**Comment by lemin9538** [comment]
是在el3里面碰到tlbi挂掉，还是在el2里面遇到tlbi挂掉？

从你的描述来看，感觉系统还没有跳转到el2，还在atf阶段。请把挂掉时候代码处截个图我看下。

**Comment by wuxiaoqiang12** [comment]
![image](https://user-images.githubusercontent.com/39110174/76809715-20cf6300-67c2-11ea-9698-3376f0dbfab4.png)
因为我设置的是Debug from entry point所以会停在_start:这里再往下执行一句tlbi会挂掉。在boot.S:87处。

**Comment by lemin9538** [comment]
这个代码是hypervisor的需要运行在el2。但是你现在还是处于el3. 没有跳转到el2. 

这就说明atf没有跳转到el2。你用的是最新的atf代码吗？

**Comment by lemin9538** [comment]
你选connect only.  我猜测你那边的atf代码压根没有运行，直接就在el3跑el2的代码

**Comment by wuxiaoqiang12** [comment]
是最新的，这个仓库master分支。[arm-trusted-firmware](https://github.com/ARM-software/arm-trusted-firmware.git)

**Comment by wuxiaoqiang12** [comment]
![image](https://user-images.githubusercontent.com/39110174/76810236-bae3db00-67c3-11ea-8676-9ee7d0f7bebc.png)
选了connect only之后是停在这里，这应该是atf的代码吧?

**Comment by lemin9538** [comment]
我待会发一个commit id给你，最新的atf我测过，用的还是18年的。

另外 你确认下，Ds5 run之前是否有停在0x04020000 (EL3)这个地址。还是一上来就直接是c0008000这个地址，是的话，那说明atf压根没运行。

**Comment by wuxiaoqiang12** [comment]
选connect only会停在0x04020000这里。

**Comment by lemin9538** [comment]
> ![image](https://user-images.githubusercontent.com/39110174/76810236-bae3db00-67c3-11ea-8676-9ee7d0f7bebc.png)
> 选了connect only之后是停在这里，这应该是atf的代码吧?

是的，那问题应该出在atf没有跳转。atf最新代码应该有变动。

**Comment by lemin9538** [comment]
git reset --hard 5f38b5362cff958225c6ad9b3d45a56b3d613fbf

你先退回到这个commit. 编译下。同时 我把我用的bl31.bin上传上来，你可以试下
https://github.com/minosproject/minos-misc/blob/master/bl31.bin

**Comment by wuxiaoqiang12** [comment]
![image](https://user-images.githubusercontent.com/39110174/76811176-0350c800-67c7-11ea-9039-a8398da63967.png)
我使用了你提供的bl31.bin选择connect only会进入EL3的0x04020000开始执行，我在debug的command中使用n(next)指令执行了一段之后会进入到EL2N,但我使用命令b _start在命令窗口中提示如下:
b _start
Breakpoint 12 at EL3:0x00000000C0008000
	on file boot.S, line 32
这里还是EL3, 接着使用c命令希望能停在_start处并不能成功，DS-5会一直处于running状态，不能停止。

**Comment by lemin9538** [comment]
你 b _start要加个参数，你试试 b EL2N:_start。

**Comment by lemin9538** [comment]
还可以 b EL2N:0xc0008000

**Comment by wuxiaoqiang12** [comment]
太感谢了。可以了，还有个小问题就是代码中pr_notice输出的消息我在哪里可以看到？

**Comment by lemin9538** [comment]
会输出到串口，ds5会启动两个串口终端，有一个是用来输出hypervisor的log的。

另外，如果你这边方便的话，希望能把你在arm-fvp上设置的过程记录下，更新到Document对应的.md文件.

**Comment by wuxiaoqiang12** [comment]
可以啊，非常乐意做。我会写一下，反正这几天也在家办公，学校不敢去了。

**Comment by lemin9538** [comment]
好的 感谢
