### ISSUE TITLE
Failure when boot Minos on FVP by DS-5

### ISSUE THREAD

**Issue by sustcstar** [minosproject/minos#50]
I follow this guideline https://github.com/minosproject/minos/blob/master/Documents/004-Test_Minos_on_ARM_FVP.md

The compiler I use is aarch64-linux-gnu-gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0

The DS-5 I use is DS-5_v5.28.0

At the step8: Boot minos on DS-5, I do as following:
1. In "Debug Configurations"/"Connection", select "ARM FVP (Installed with DS-5)/Base_AEMv8Ax4/Bare Metal Debug/Debug ARMAEMv8-A_x4 SMP", In the "model parameters", copy the following settings in it:
-C pctl.startup=0.0.0.0 \ -C bp.secure_memory=0 \ -C cluster0.NUM_CORES=4 \ -C cache_state_modelled=0 \ -C cluster0.cpu0.RVBAR=0x04020000 \ -C cluster0.cpu1.RVBAR=0x04020000 \ -C cluster0.cpu2.RVBAR=0x04020000 \ -C cluster0.cpu3.RVBAR=0x04020000 \ -C bp.hostbridge.userNetPorts="8023=22" \ -C bp.hostbridge.userNetworking=true \ -C bp.dram_size=8 \ -C bp.smsc_91c111.enabled=true \ -C bp.virtioblockdevice.image_path=/home/chenyinhua/minos-workspace/arm-fvp/sd.img \ --data cluster0.cpu0=/home/chenyinhua/minos-workspace/arm-fvp/bl31.bin@0x04020000 \ --data cluster0.cpu0=/home/chenyinhua/minos-workspace/arm-fvp/Image@0x80080000 \ --data cluster0.cpu0=/home/chenyinhua/minos-workspace/arm-fvp/minos.bin@0xc0008000 \ --data cluster0.cpu0=/home/chenyinhua/minos-workspace/arm-fvp/fdt.dtb@0xc3e00000 --data cluster0.cpu0=/home/chenyinhua/minos-workspace/arm-fvp/fvp_linux.dtb@0x83e00000

![Connection](https://user-images.githubusercontent.com/44500207/113564810-8e079d80-963c-11eb-9f0e-c39133e38041.png)

2. In Debugger, set as the following figure:

![Debugger](https://user-images.githubusercontent.com/44500207/113564872-a8417b80-963c-11eb-825c-0cef7c2361df.png)

3. Press Debug, and the error comes out:

========== Connection Failed==========
The script file ( rtsm_launcher.py ) failed during execution:
Failed to launch model FVP_Base_AEMv8A. Command:
  /usr/local/DS-5_v5.28.0/bin/FVP_Base_AEMv8A --cadi-server --print-port-number -C pctl.startup=0.0.0.0  -C bp.secure_memory=0  -C cluster0.NUM_CORES=4  -C cache_state_modelled=0  -C cluster0.cpu0.RVBAR=0x04020000  -C cluster0.cpu1.RVBAR=0x04020000  -C cluster0.cpu2.RVBAR=0x04020000  -C cluster0.cpu3.RVBAR=0x04020000  -C bp.hostbridge.userNetPorts=8023=22  -C bp.hostbridge.userNetworking=true  -C bp.dram_size=8  -C bp.smsc_91c111.enabled=true  -C bp.virtioblockdevice.image_path=/home/chenyinhua/minos-workspace/arm-fvp/sd.img  --data cluster0.cpu0=/home/chenyinhua/minos-workspace/arm-fvp/bl31.bin@0x04020000  --data cluster0.cpu0=/home/chenyinhua/minos-workspace/arm-fvp/Image@0x80080000  --data cluster0.cpu0=/home/chenyinhua/minos-workspace/arm-fvp/minos.bin@0xc0008000  --data cluster0.cpu0=/home/chenyinhua/minos-workspace/arm-fvp/fdt.dtb@0xc3e00000 --data cluster0.cpu0=/home/chenyinhua/minos-workspace/arm-fvp/fvp_linux.dtb@0x83e00000
exited with error code: 1

See Target Console view for more details

![Connection failed](https://user-images.githubusercontent.com/44500207/113566355-21da6900-963f-11eb-8e92-ccd6692009f5.png)

==================Target Console===============

FVP_Base_AEMv8A: ' -C': application file not found
Info: /OSCI/SystemC: Simulation stopped by user.

![Target Console](https://user-images.githubusercontent.com/44500207/113566377-299a0d80-963f-11eb-98ff-a16a3594a239.png)

**Comment by lemin9538** [comment]
You need remove the '\' before -C. And you'd better checkout the code to version 0.3.2，since there are some new features recently, but the document has not been update at the same time.

**Comment by sustcstar** [comment]
> You need remove the '' before -C. And you'd better checkout the code to version 0.3.2，since there are some new features recently, but the document has not been update at the same time.

I delete all the "\" in Model parameters in DS-5, and it works!

Thanks for your help!
