### ISSUE TITLE
How to use qemu run minos 

### ISSUE THREAD

**Issue by SearchTheTruth** [minosproject/minos#58]
Hi,  I'm not familiar to qemu and uboot and do much effort to try to run minos by qemu, but it still can't work.
Is there any documents related about how to use qemu run minos?
Thanks a lot.

**Comment by lemin9538** [comment]
Hi，I will write a document about this topic soom.

**Comment by lemin9538** [comment]
Hi you can refers to [https://github.com/minosproject/minos/blob/master/Documents/005-Run_Minos_on_Qemu.md](url)

**Comment by SearchTheTruth** [comment]
It's help a lot!
Thank you :)
