### ISSUE TITLE
agherzan/u-boot.git doesn't work

### ISSUE THREAD

**Issue by liuzuanmin** [minosproject/minos#7]
Hi LeMin,
sorry for inconvenience you.
https://github.com/minosproject/minos-hypervisor/blob/master/Documents/002-Test_Minos_on_Raspberry_4.md

https://github.com/agherzan/u-boot.git

which branch do you choose? the default one doesn't have rpi_4_defconfig.

**Comment by lemin9538** [comment]
It should be ag/rpi4 branch

**Comment by liuzuanmin** [comment]
> Hi please try ag/rpi4 branch.

Thanks for your quickly reply.
It is not lucky that minicom didn't get response on /dev/hvc1 after all instructions on page 002-Test_Minos_on_Raspberry_4.md.

**Comment by lemin9538** [comment]
Please provide your log and command.  Thanks

**Comment by liuzuanmin** [comment]
> Please provide your log and command.
> 
> 如果是默认的native vm，现在默认使用的是debug console. 你可以试试:
> 1- Ctrl + D
> 2- tty attach vm1

cool !!
work very well on vm1, thanks very much. 
no response on vm2(zephyr), could you give some solutions?

[com.log](https://github.com/minosproject/minos-hypervisor/files/4495986/com.log)

**Comment by lemin9538** [comment]
你可以下载 https://github.com/minosproject/zephyr 代码切换到minos-aarch64分支重新编译一个zephyr.bin。

或者你直接使用minos-misc里面我编译好的，之前里面的zephyr.bin不支持debug_console, 我更新了一个新的，你替换下就可以

**Comment by liuzuanmin** [comment]
> 你可以下载 https://github.com/minosproject/zephyr 代码切换到minos-aarch64分支重新编译一个zephyr.bin。
> 
> 或者你直接使用minos-misc里面我编译好的，之前里面的zephyr.bin不支持debug_console, 我更新了一个新的，你替换下就可以

work well by replace. great project!
![image](https://user-images.githubusercontent.com/6505472/79627920-fa109d80-816e-11ea-8612-9be9c70e369d.png)

**Comment by lemin9538** [comment]
Also thanks for you feedback.
